Utils: Update genrprc utility to invoke gencmbelf
The genrprc utility has been updated to invoke gencmbelf
utility to generate a combined ELF image, using stripped
versions of the passed in ELF images, but only after
retrieving the needed symbols from the input files. The
syntax is same as the previous version, but all the input
and output files are expected to the ELF M3 files.

These symbols are retrieved from Core1 image file and
used for updating the associated entries in the resource
table which is present only in Core0 image. Currently,
only the symbols needed for the Core1 trace entry are
retrieved.

Signed-off-by: Suman Anna <s-anna@ti.com>

diff --git a/src/utils/genrprc b/src/utils/genrprc
--- a/src/utils/genrprc
+++ b/src/utils/genrprc
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2011-2012, Texas Instruments Incorporated
+# Copyright (c) 2011-2013, Texas Instruments Incorporated
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -32,48 +32,25 @@
 #
 #===============================================================================
 #
-# Usage: genrprc [--e0=core0 entry point] [--e1=core1 entry point]
-#          [--t0=core0 trace buffer symbol] [--t1=core1 trace buffer symbol]
-#          [--d0=core0 error buffer symbol] [--d1=core1 error buffer symbol]
-#          [--s0=core0 suspend symbol]      [--s1=core1 suspend symbol]
-#          core0_filename [core1_filename] output_filename
+# Usage: genrprc [--t0=core0 trace buffer symbol] [--t1=core1 trace buffer symbol]
+#          core0_filename core1_filename output_filename
 #
 # Default values for:
-#   core0 entry point: "Entry point address:" field from output of
-#                      'readelf -h core0_filename'
-#   core1 entry point: "Entry point address:" field from output of
-#                      'readelf -h core1_filename'
 #   core0 trace buffer symbol: SysMin_Module_State_0_outbuf__A
 #   core1 trace buffer symbol: SysMin_Module_State_0_outbuf__A
-#   core0 error buffer symbol: Deh_Module_State_0_outbuf__A
-#   core1 error buffer symbol: Deh_Module_State_0_outbuf__A
-#   core0 suspend addr symbol: ti_sysbios_family_arm_ducati_omap4430_readyIdleCore0 (non-SMP)
-#                              ti_sysbios_family_arm_ducati_smp_readyIdleCore0 (SMP)
-#                              ti_sysbios_family_c64p_tesla_Power_readyIdle (DSP)
-#   core1 suspend addr symbol: ti_sysbios_family_arm_ducati_omap4430_readyIdleCore1
 #
 #===============================================================================
 
 usage=\
-"Usage: genrprc [--e0=core0 entry point] [--e1=core1 entry point]
-        [--t0=core0 trace buffer symbol] [--t1=core1 trace buffer symbol]
-        [--d0=core0 error buffer symbol] [--d1=core1 error buffer symbol]
-        [--s0=core0 suspend symbol]      [--s1=core1 suspend symbol]
-        core0_filename [core1_filename] output_filename"
+"Usage: genrprc [--t0=core0 trace buffer symbol] [--t1=core1 trace buffer symbol]
+        core0_filename core1_filename output_filename"
 
 dir=`dirname $0`
 
 tracename0=SysMin_Module_State_0_outbuf__A
 tracename1=SysMin_Module_State_0_outbuf__A
-entryname0=
-entryname1=
-errbufname0=Deh_Module_State_0_outbuf__A
-errbufname1=Deh_Module_State_0_outbuf__A
-suspname0=ti_sysbios_family_arm_ducati_omap4430_readyIdleCore0
-suspname1=ti_sysbios_family_arm_ducati_omap4430_readyIdleCore1
-smpsuspname0=ti_sysbios_family_arm_ducati_smp_readyIdleCore0
 
-cmdline=`getopt -o "" --long e0:,e1:,t0:,t1:,d0:,d1:,s0:,s1: --name $0 -- "$@"`
+cmdline=`getopt -o "" --long t0:,t1:, --name $0 -- "$@"`
 err=$?
 if [[ $err != 0 ]]
 then
@@ -86,275 +63,91 @@ fi
 eval set -- "$cmdline"
 while true ; do
     case "$1" in
-	--e0) entryname0=$2; shift 2;;
-	--e1) entryname1=$2; shift 2;;
 	--t0) tracename0=$2; shift 2;;
 	--t1) tracename1=$2; shift 2;;
-	--d0) errbufname0=$2; shift 2;;
-	--d1) errbufname1=$2; shift 2;;
-	--s0) suspname0=$2; shift 2;;
-	--s1) suspname1=$2; shift 2;;
 	--) shift; break;;
     esac
 done
 
-ext=`basename $1 | awk -F . '{print $NF}'`
-if [[ $ext == "xe64T" ]]
-then
-	if  [[ $entryname0 == "" ]]
-	then
-		echo warning: ti_sysbios_family_c64p_Hwi0 is being set as entry point for dsp
-		entryname0=ti_sysbios_family_c64p_Hwi0
-	fi
-	if [[ $suspname0 == "ti_sysbios_family_arm_ducati_omap4430_readyIdleCore0" ]]
-	then
-		suspname0=ti_sysbios_family_c64p_tesla_Power_readyIdle
-	fi
-fi
-
+# exit if all the files are not passed in
 if [[ $# == 3 ]]
 then
 	core0file=$1
 	core1file=$2
 	outfile=$3
 	shift 3
-
-	traceaddr0=`nm $core0file | grep $tracename0 | cut -d ' ' -f 1`
-	traceaddr1=`nm $core1file | grep $tracename1 | cut -d ' ' -f 1`
-	errbufaddr0=`nm $core0file | grep $errbufname0 | cut -d ' ' -f 1`
-	errbufaddr1=`nm $core1file | grep $errbufname1 | cut -d ' ' -f 1`
-	suspaddr0=`nm $core0file | grep $suspname0 | cut -d ' ' -f 1`
-	suspaddr1=`nm $core1file | grep $suspname1 | cut -d ' ' -f 1`
-	if [[ $entryname0 == "" ]]
-	then
-		entryaddr0=`readelf -h $core0file | \
-		  grep "Entry point address" | awk '{printf($4)}'`
-	else
-		entryaddr0=`nm $core0file | \
-		  grep $entryname0 | awk '{printf($1)}'`
-	fi
-	if [[ $entryname1 == "" ]]
-	then
-		entryaddr1=`readelf -h $core1file | \
-		  grep "Entry point address" | awk '{printf($4)}'`
-	else
-		entryaddr1=`nm $core1file | \
-		  grep $entryname1 | awk '{printf($1)}'`
-	fi
 else
-    if [[ $# == 2 ]]
-    then
-	core0file=$1
-	outfile=$2
-	shift 2
-
-	traceaddr0=`nm $core0file | grep $tracename0 | cut -d ' ' -f 1`
-	errbufaddr0=`nm $core0file | grep $errbufname0 | cut -d ' ' -f 1`
-	suspaddr0=`nm $core0file | grep $suspname0 | cut -d ' ' -f 1`
-	if [[ $suspaddr0 == "" ]]
-	then
-		suspaddr0=`nm $core0file | grep $smpsuspname0 | cut -d ' ' -f 1`
-	fi
-	if [[ $entryname0 == "" ]]
-	then
-		entryaddr0=`readelf -h $core0file | \
-		  grep "Entry point address" | awk '{printf($4)}'`
-	else
-		entryaddr0=`nm $core0file | \
-		  grep $entryname0 | awk '{printf($1)}'`
-	fi
-    else
 	echo $usage
 	exit 1
-    fi
 fi
 
+# make sure output file has an ELF ARM M3 extension and remove if exists
+ext=`basename $outfile | awk -F . '{print $NF}'`
+if [[ $ext != "xem3" ]]
+then
+	echo error: outfile file \'$outfile\' does not have xem3 extension
+	echo $usage
+	exit 1
+fi
+if [[ -f $outfile ]]
+then
+	echo warning: deleting existing output file
+	rm $outfile
+fi
+
+# make sure core0 file is an ELF ARM M3 executable
 if [[ -f $core0file ]]
 then
-	if [[ $entryaddr0 == "" ]]
+	ext=`basename $core0file | awk -F . '{print $NF}'`
+	if [[ $ext != "xem3" ]]
 	then
-		echo warning: null entry point for core 0
+		echo error: core0 input file \'$core0file\' does not have xem3 extension
+		echo $usage
+		exit 1
 	fi
-
-	if [[ $traceaddr0 == "" ]]
-	then
-		echo warning: null trace buffer address for core 0
-	fi
-
-	if [[ $errbufaddr0 == "" ]]
-	then
-		echo warning: null error buffer address for core 0
-	fi
-	if [[ $suspaddr0 == "" ]]
-	then
-		echo warning: null suspend address
-	fi
+else
+	echo error: core0 input file \'$core0file\' does not exist
+	echo $usage
+	exit 1
 fi
 
-if [[ -f $core1file ]]
-then
-	if [[ $entryaddr1 == "" ]]
-	then
-		echo warning: null entry point for core 1
-	fi
-	if [[ $traceaddr1 == "" ]]
-	then
-		echo warning: null trace buffer address for core 1
-	fi
-	if [[ $errbufaddr1 == "" ]]
-	then
-		echo warning: null error buffer address for core 1
-	fi
-	if [[ $suspaddr1 == "" ]]
-	then
-		if [[ $suspaddr0 != "" ]]
-		then
-			echo error: pm package should be included in both/none of the cores
-			exit 1
-		fi
-	else
-		if [[ $suspaddr0 == "" ]]
-		then
-			echo error: pm package should be included in both/none of the cores
-			exit 1
-		fi
-	fi
-fi
-
-file_info=`file $outfile`
+# make sure it is a proper executable file
+file_info=`file $core0file`
 foo=`echo $file_info | grep executable`
-#
-# Make sure we don't overwrite executable.
-# User might have mistakenly forgotten to specify output file name.
-#
-if [[ $foo != "" ]]
+if [[ $foo == "" ]]
 then
-	echo error: output file \'$outfile\' is of type \"executable\" but should be a data file
+	echo error: output file \'$core0file\' is not of type \"executable\" but should be one
 	echo $usage
 	exit 1
 fi
 
-tmp=/tmp/genrprc-$$
+# make sure core1 file is an ELF ARM M3 executable
 if [[ -f $core1file ]]
 then
-	echo $dir/mkheader $core0file $core1file $outfile
-	$dir/mkheader $core0file $core1file $outfile
+	ext=`basename $core1file | awk -F . '{print $NF}'`
+	if [[ $ext != "xem3" ]]
+	then
+		echo error: core1 input file \'$core1file\' does not have xem3 extension
+		echo $usage
+		exit 1
+	fi
 else
-	echo $dir/mkheader $core0file $outfile
-	$dir/mkheader $core0file $outfile
-fi
-
-
-if [[ $? != 0 ]]
-then
-	echo mkheader failed
+	echo error: core1 input file \'$core1file\' does not exist
 	echo $usage
 	exit 1
 fi
 
-#
-# genbase (invoked below) accepts any number of "key:value" tags on its
-# command invocation.  Today, the supported tags are:
-#	restab:<hex-addr>
-#	trace[0-9]:<hex-addr>
-#	errbuf[0-9]:<hex-addr>
-#	entry[0-9]:<hex-addr>
-# where <hex-addr> is an address in hexadecimal form w/ or w/o leading "0x",
-# and the [0-9] field specifies a "core number".
-#
-# restab is the key name for the (possibly nonexistant) .resource_table
-# linker section, and its value is the section's address.  When genbase
-# encounters a linker section whose address matches the restab value, it
-# calls a special resource table processing function for that section.
-#
-# trace[0-9] is the key name for core 0's executable file's trace buffer,
-# and its value is the trace buffer's address.  When genbase encounters
-# a resource (from the .resource_table table) of type TRACE it assigns
-# that resource's "base" element to the value of key trace[0-9] (the 1st
-# type TRACE resource gets the value of trace0, the 2nd type TRACE resource
-# gets the value of trace1, etc.).
-#
-# errbuf[0-9] is the key name for core 0's executable file's crash-dump buffer,
-# and its value is the crash-dump buffer's address.  When genbase encounters
-# a resource (from the .resource_table table) of type ERRBUF it assigns
-# that resource's "base" element to the value of key errbuf[0-9] (the 1st
-# type ERRBUF resource gets the value of errbuf0, the 2nd type ERRBUF resource
-# gets the value of errbuf1, etc.).
-#
-# entry[0-9] is the key name for core 0's executable file's entry point,
-# and its value is the entry point's address.  When genbase encounters
-# a resource (from the .resource_table table) of type ENTRYPOINT it assigns
-# that resource's "base" element to the value of key entry[0-9] (the 1st
-# type ENTRYPOINT resource gets the value of entry0, the 2nd type ENTRYPOINT
-# resource gets the value of entry1, etc.).
-#
-
-if [[ -f $core0file ]]
+# make sure it is a proper executable file
+file_info=`file $core1file`
+foo=`echo $file_info | grep executable`
+if [[ $foo == "" ]]
 then
-	t0Size=`readelf -S $core0file | \
-	  awk '{if ($2==".tracebuf") printf("%s", $6)}'`
-else
-	t0Size=0
+	echo error: output file \'$core1file\' is not of type \"executable\" but should be one
+	echo $usage
+	exit 1
 fi
 
-if [[ -f $core1file ]]
-then
-	t1Size=`readelf -S $core1file | \
-	  awk '{if ($2==".tracebuf") printf("%s", $6)}'`
-else
-	t1Size=0
-fi
-
-if [[ -f $core0file ]]
-then
-	d0Size=`readelf -S $core0file | \
-	  awk '{if ($2==".errorbuf") printf("%s", $6)}'`
-else
-	d0Size=0
-fi
-
-if [[ -f $core1file ]]
-then
-	d1Size=`readelf -S $core1file | \
-	  awk '{if ($2==".errorbuf") printf("%s", $6)}'`
-else
-	d1Size=0
-fi
-
-args=
-if [[ $traceaddr0 != "" ]]
-then
-	args="$args trace0:$traceaddr0:$t0Size"
-fi
-if [[ $traceaddr1 != "" ]]
-then
-	args="$args trace1:$traceaddr1:$t1Size"
-fi
-if [[ $errbufaddr0 != "" ]]
-then
-	args="$args errbuf0:$errbufaddr0:$d0Size"
-fi
-if [[ $errbufaddr1 != "" ]]
-then
-	args="$args errbuf1:$errbufaddr1:$d1Size"
-fi
-if [[ $entryaddr0 != "" ]]
-then
-	args="$args entry0:$entryaddr0:0"
-fi
-if [[ $entryaddr1 != "" ]]
-then
-	args="$args entry1:$entryaddr1:0"
-fi
-if [[ $suspaddr0 != "" ]]
-then
-	args="$args susp0:$suspaddr0:0"
-fi
-if [[ $suspaddr1 != "" ]]
-then
-	args="$args susp1:$suspaddr1:0"
-fi
-
+# make sure core0 file has a resource table
 if [[ -f $core0file ]]
 then
 	resource_tab=`readelf -S $core0file | \
@@ -363,34 +156,64 @@ then
 	  awk '{if ($2==".resource_table") printf("%s", $6)}'`
 	if [[ $resource_tab == "" ]]
 	then
-		echo no .resource_tab section found in $core0file
-		echo $dir/genbase $core0file $tmp $*
-		$dir/genbase $core0file $tmp $*
-	else
-		echo $dir/genbase $core0file $tmp $* restab:$resource_tab:$r_size $args
-		$dir/genbase $core0file $tmp $* restab:$resource_tab:$r_size $args
+		echo error: Core0 file \'$core0file\' is missing the resource table.
+		echo $usage
+		exit 1
 	fi
-	cat $tmp >> $outfile
-	rm $tmp
 fi
 
+traceaddr0=`nm $core0file | grep $tracename0 | cut -d ' ' -f 1`
+traceaddr1=`nm $core1file | grep $tracename1 | cut -d ' ' -f 1`
+t0Size=`readelf -S $core0file | \
+		awk '{if ($2==".tracebuf") printf("%s", $6)}'`
+t1Size=`readelf -S $core1file | \
+		awk '{if ($2==".tracebuf") printf("%s", $6)}'`
 
-if [[ -f $core1file ]]
+core0stripfile=core0-tmp.xem3
+core1stripfile=core1-tmp.xem3
+
+#
+# gencmbelf (invoked below) accepts any number of "key:value" tags on its
+# command invocation.  Today, the supported tags are:
+#	trace[0-9]:<hex-addr>
+# where <hex-addr> is an address in hexadecimal form w/ or w/o leading "0x",
+# and the [0-9] field specifies a "core number".
+#
+# trace[0-9] is the key name for core 0's executable file's trace buffer,
+# and its value is the trace buffer's address.  When gencmbelf encounters
+# a resource (from the .resource_table table) of type TRACE it assigns
+# that resource's "base" element to the value of key trace[0-9] (the 1st
+# type TRACE resource gets the value of trace0, the 2nd type TRACE resource
+# gets the value of trace1, etc.). Only trace1 will be updated today as the
+# trace0 in the core0 resource table already reflects the correct base and
+# size.
+#
+
+args=
+if [[ $traceaddr0 != "" ]]
 then
-	resource_tab=`readelf -S $core1file | \
-	  awk '{if ($2==".resource_table") printf("%s", $4)}'`
-	r_size=`readelf -S $core1file | \
-	  awk '{if ($2==".resource_table") printf("%s", $6)}'`
-	if [[ $resource_tab == "" ]]
-	then
-		echo no .resource_tab section found in $core1file
-		echo $dir/genbase $core1file $tmp $*
-		$dir/genbase $core1file $tmp $*
-	else
-		echo $dir/genbase $core0file $tmp $* restab:$resource_tab:$r_size $args
-		$dir/genbase $core0file $tmp $* restab:$resource_tab:$r_size $args
-	fi
-
-	cat $tmp >> $outfile
-	rm $tmp
+	args="$args trace0:$traceaddr0:$t0Size"
+else
+	echo warning: null trace buffer address for core 0
 fi
+if [[ $traceaddr1 != "" ]]
+then
+	args="$args trace1:$traceaddr1:$t1Size"
+else
+	echo warning: null trace buffer address for core 1
+fi
+
+# strip the input images of all symbols and debug info
+$TMS470CGTOOLPATH/bin/armstrip -p $core0file -o $core0stripfile
+$TMS470CGTOOLPATH/bin/armstrip -p $core1file -o $core1stripfile
+
+#
+# invoke gencmbelf to generate a single combined output file
+# using the stripped images
+#
+echo $dir/gencmbelf $core0stripfile $core1stripfile $outfile
+$dir/gencmbelf $core0stripfile $core1stripfile $outfile
+
+# remove the generated intermediate stripped images
+rm $core0stripfile
+rm $core1stripfile
